### ISSUE TITLE
todo: '~22.05.15 생활코딩[react] , 생활코딩[react 2020 개정판] 수강 완료

### ISSUE THREAD

**Issue by DeukHan** [DeukHan/Study-Web#2]
- [x] 생활코딩[react]
- [ ] 생활코딩[react 2020 개정판]

**Comment by dev-heeseok** [comment]
@DeukHan 
[스타일 가이드](https://blog.munilive.com/posts/my-git-commit-guide.html) 입니다
참고바랍니다

**Comment by dev-heeseok** [comment]
@DeukHan 
스터디 완료인가요??
클로즈 되었네요

**Comment by DeukHan** [comment]
2020 스터디에 대한 이슈를 새로 만들려고 합니다.
있던거에서 계속 하는게 나을까요?
@dev-heeseok
